# Generated by Django 5.1.1 on 2024-09-28 23:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("runs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="run",
            name="time",
            field=models.IntegerField(help_text="Time taken for the run in seconds"),
        ),
    ]
